Ce/Presentation/CeShi/Controllers/Admin/ParameterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CeShi.Controllers.Admin
{
    public class ParameterController : Controller
    {
        public List<ParameterInfo> paralist = new List<ParameterInfo>();
        public ActionResult Index()
        {
            init();
            return View(paralist);
        }

        public void init()
        {
            ParameterInfo para1 = new ParameterInfo() { ParaID=1,ParaName = "service", ParaType = "string(20)", ParaIsNull = 0, ParaDescription = "服务名，必填，且必须在User_ServiceInfo表里存在该服务名（ServiceName字段）", ParaExample = "" };
            ParameterInfo para2 = new ParameterInfo() { ParaID=2,ParaName = "username", ParaType = "string(20)", ParaIsNull = 1, ParaDescription = "用户名，userid和username至少传一个，不能有单引号", ParaExample = "" };
            ParameterInfo para3 = new ParameterInfo() { ParaID = 3, ParaName = "userid", ParaType = "string(20)", ParaIsNull = 1, ParaDescription = "用户ID，userid和username至少传一个，纯数字", ParaExample = "" };
            ParameterInfo para4 = new ParameterInfo() { ParaID = 4, ParaName = "soufuncard", ParaType = "string(20)", ParaIsNull = 1, ParaDescription = "是否返回搜房卡信息，1是，可选", ParaExample = "" };
            paralist.Add(para1);
            paralist.Add(para2);
            paralist.Add(para3);
            paralist.Add(para4);
        }

    }



    public class ParameterInfo
    {
        public int ParaID { get; set; }
        public string ParaName { get; set; }
        public string ParaType { get; set; }
        public int ParaIsNull { get; set; }
        public string ParaDescription { get; set; }
        public string ParaExample { get; set; }
    }


}

Ce/Presentation/CeShi/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CeShi.Controllers
{
    public class AdminController : Controller
    {
        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 导航栏
        /// </summary>
        public ActionResult NavBar()
        {      
            return View();
        }

        /// <summary>
        /// 菜单栏
        /// </summary>
        public ActionResult Menu()
        {           
            return View();
        }

        /// <summary>
        /// 商城运行信息
        /// </summary>
        public ActionResult RunInfo()
        {
         
            return View();
        }
        /// <summary>
        /// 底部
        /// </summary>
        /// <returns></returns>
        public ActionResult Bottom()
        {
            return View();
        }

    }
}

Ce/Presentation/CeShi/Controllers/HomeController.cs
using Services;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Helper;

namespace Ce.Controllers
{
    public class HomeController : BaseWebController
    {       
        public ActionResult Index()
        {                           
            return View(WorkContext);                       
        }

        public ActionResult CheckLogin()
        {         
            string getUsername = WebHelper.GetRequestString("username");
            string getUserpwd = WebHelper.GetRequestString("userpwd");
            //判断是不是含有该用户名
            if (Sv_Login.CheckExistThisUser(getUsername))
            {
                IOHelper.WriteLog(getUsername+"登录成功");
                return Content("登录成功，用户名为"+getUsername+",密码为"+ getUserpwd);               
            }
            return Content("不存在此用户");                    
        }
   
    }

}

Ce/Presentation/CeShi/Controllers/SecKillController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Core.Helper;

namespace CeShi.Controllers
{
    // localhost:6335/SecKill/Index?Pid=1764&city=sh

    public class SecKillController : Controller
    {
        #region 活动信息相关成员
        //spikeProj表
        protected string ProjId = "";
        protected string ProjName = "";
        //spikeActivity表
        protected string RunningId = "";
        protected string RunningspikeTime = "";
        protected string RunningpicLink = "";
        protected string RunningheadImgUrl = "";
        protected string RunningpicUrl = "";
        protected string RunningselNum = "";
        protected string Runningprize = "";
        protected string RunningwinnerShow = "";
        protected string RunningnowinnerShow = "";
        //其他
        protected string errorMsg = "";
        protected string hidPhone = "";

        #endregion

        #region 活动中判断相关状态成员
        protected string Cmd = "";
        protected bool IsRunning = false; //是否活动正在进行中
        protected bool IsUserlogin = false;//是否用户已报名，处于登录状态
        protected bool IsJustEnd = false;//是否上次活动刚结束，且结束还没超过10分钟
        protected bool IsCheckCode = false;//是否启用验证码
        #endregion

        public ActionResult Index()
        {          
            return View();
        }

      
        public ActionResult ReturnNowTime()
        {
            string timeStr = "", nowtime = "";
            if (WebHelper.GetRequestString("id").Trim() != "" && Regex.IsMatch(WebHelper.GetRequestString("id").Trim(), @"^[1-9][0-9]*$"))
            {
                RunningId = WebHelper.GetRequestString("id").Trim();
            }         
            if (Regex.IsMatch(RunningId, @"^[1-9][0-9]*$"))
            {
                DataTable dt = DBHelper.GetDataTable("select top 1 *,getdate() as nowtime from spikeActivity where id=" + RunningId);
                if (dt != null && dt.Rows.Count > 0)
                {
                    timeStr = dt.Rows[0]["spikeTime"].ToString();
                    nowtime = dt.Rows[0]["nowtime"].ToString();

                    if (!String.IsNullOrEmpty(timeStr))
                    {
                        bool flag = true;
                        if (DateTime.Parse(nowtime) <= DateTime.Parse(timeStr))
                        {
                            flag = false;
                            return Content((DateTime.Parse(timeStr) - DateTime.Parse(nowtime)).TotalSeconds.ToString("f0") + ",1");
                        }
                        if (flag) //已结束
                        {
                            return Content("-1");
                        }
                    }
                    return Content("db");
                }
                else
                {
                    return Content("db");
                }
            }
            else
            {
                return Content("err");
            }
        }     
    }
}

Ce/Presentation/CeShi/Controllers/UploadImgController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Configuration;

namespace CeShi.Controllers
{
    public class UploadImgController : Controller
    {      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveUploadSource(HttpPostedFileBase Filedata)
        {
            var actionResult = default(ContentResult);
            bool flag = false;
            var message = "";
            var filetype = "";
            var filesize = "";
            var filewidth = "";
            var fileheight = "";
            var fileurl = "";
            var newid = Guid.NewGuid().ToString("N");
            try
            {
                // 如果没有上传文件
                if (Filedata == null || string.IsNullOrEmpty(Filedata.FileName) || Filedata.ContentLength == 0)
                {
                    message = "找不到要上传的文件，请重新上传";
                }
                else
                {
                    // 保存到  指定位置                   
                    string fileExtension = Filedata.FileName.Substring(Filedata.FileName.LastIndexOf('.'));

                    string fullFileName = newid + fileExtension;
                    // 文件系统不能使用虚拟路径
                    string uploadPath = Server.MapPath("~/Files/Upload/" + DateTime.Now.ToString("yyyyMMdd") + "/");
                    Directory.CreateDirectory(uploadPath);
                    Filedata.SaveAs(uploadPath + fullFileName);
                    System.Drawing.Image image = System.Drawing.Image.FromFile(uploadPath + fullFileName);
                    filewidth = image.Width.ToString(); ;
                    fileheight = image.Height.ToString();
                    filetype = Filedata.FileName.Substring(Filedata.FileName.LastIndexOf('.') + 1).ToUpper(); ;
                    filesize = Filedata.ContentLength.ToString();
                    fileurl =ConfigurationManager.AppSettings["WebDomain"]+ "/Files/Upload/" + DateTime.Now.ToString("yyyyMMdd") + "/" + fullFileName;
                    message = "上传成功";
                    flag = true;
                }
                actionResult = new ContentResult
                {
                    Content = new JavaScriptSerializer().Serialize(new
                    {
                        Message = message,
                        Flag = flag ? 1 : 0,
                        ftype = filetype,
                        image_width = filewidth,
                        image_height = fileheight,
                        fsize = filesize,
                        furl = fileurl,
                        fid = newid
                    })
                };
            }
            catch (Exception ex)
            {
                message = "上传遇到问题，请重试，问题描述：" + ex.Message;
                flag = false;
            }
            return actionResult;
        }




        //第二种
        #region 图片上传

        public ActionResult Preview(string baseimg)
        {
            //string url = "http://imgtest.fang.com/Upload/UploadFile";
            //string url = "http://imgu.soufun.com/upload/pic?channel=zhongchou.pic&city=&isflash=y";
            string url = "http://imgu.fang.com/upload/pic?isflash=y&channel=kanli.pic&city=";//低于5M大小的图片 

            string html = PostData3(url, 1000000, "filedata", @"D:\upload\123.jpg", baseimg.Split(',')[1]);//方法3

            return this.Json(new { Response = html });
        }
        #region 方法三
        public string PostData3(string url, int timeOut, string fileKeyName, string filePath, string base64str)
        {
            string responseContent;
            var memStream = new MemoryStream();
            var webRequest = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(url);
            // 边界符
            var boundary = "------------" + DateTime.Now.Ticks.ToString("x");
            // 编码边界符
            var firstBoundary = System.Text.Encoding.ASCII.GetBytes("--" + boundary + "\r\n");//拼接第一个form表单值用到
            var encodingBoundary = System.Text.Encoding.ASCII.GetBytes("\r\n--" + boundary + "\r\n");
            var endBoundary = System.Text.Encoding.ASCII.GetBytes("\r\n--" + boundary + "--\r\n");
            MemoryStream fileStream = new MemoryStream(Convert.FromBase64String(base64str)); //base64编码方式
            //var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);//本地读取方式

            // 设置属性
            webRequest.Method = "POST";
            webRequest.Timeout = timeOut;
            webRequest.ContentType = "multipart/form-data; boundary=" + boundary;

            #region 第一个form key-value 值  非必须
            //memStream.Write(firstBoundary, 0, firstBoundary.Length);//add
            //string partTop = "Content-Disposition: form-data; name=\"Filename\"\r\n\r\n123.jpg";//add
            //var partTopByte = Encoding.UTF8.GetBytes(partTop);//add
            //memStream.Write(partTopByte, 0, partTopByte.Length);//add   form表单 
            #endregion

            #region file表单值
            const string filePartHeader =
                    "Content-Disposition: form-data; name=\"{0}\"; filename=\"{1}\"\r\n" +
                     "Content-Type: application/octet-stream\r\n\r\n";
            var header = string.Format(filePartHeader, fileKeyName, "123.jpg");
            var headerbytes = System.Text.Encoding.UTF8.GetBytes(header);

            memStream.Write(encodingBoundary, 0, encodingBoundary.Length);
            memStream.Write(headerbytes, 0, headerbytes.Length);

            var buffer = new byte[1024];
            int bytesRead; // =0
            while ((bytesRead = fileStream.Read(buffer, 0, buffer.Length)) != 0)
            {
                memStream.Write(buffer, 0, bytesRead);
            }
            #endregion

            #region 最后一个form key-value值 非必须
            //memStream.Write(encodingBoundary, 0, encodingBoundary.Length);//add
            //string partBottom = "Content-Disposition: form-data; name=\"Upload\"\r\n\r\nSubmit Query";//add
            //var partBottomByte = Encoding.UTF8.GetBytes(partBottom);//add
            //memStream.Write(partBottomByte, 0, partBottomByte.Length);//add  form表单 
            #endregion

            // 写入最后的结束边界符
            memStream.Write(endBoundary, 0, endBoundary.Length);

            #region 上面代码拼接的 Request Payload格式
            //------------Ij5Ef1GI3cH2GI3gL6Ef1ae0cH2KM7
            //Content-Disposition: form-data; name="Filename"

            //123.jpg
            //------------Ij5Ef1GI3cH2GI3gL6Ef1ae0cH2KM7
            //Content-Disposition: form-data; name="filedata"; filename="timg.jpg"
            //Content-Type: application/octet-stream


            //------------Ij5Ef1GI3cH2GI3gL6Ef1ae0cH2KM7
            //Content-Disposition: form-data; name="Upload"

            //Submit Query
            //------------Ij5Ef1GI3cH2GI3gL6Ef1ae0cH2KM7--
            #endregion


            webRequest.ContentLength = memStream.Length;

            var requestStream = webRequest.GetRequestStream();

            memStream.Position = 0;
            var tempBuffer = new byte[memStream.Length];
            memStream.Read(tempBuffer, 0, tempBuffer.Length);
            memStream.Close();

            requestStream.Write(tempBuffer, 0, tempBuffer.Length);
            requestStream.Close();

            var httpWebResponse = (System.Net.HttpWebResponse)webRequest.GetResponse();

            using (var httpStreamReader = GetWebContent(httpWebResponse))
            {
                responseContent = httpStreamReader.ReadToEnd();
            }

            fileStream.Close();
            httpWebResponse.Close();
            webRequest.Abort();

            return responseContent;
        }
        #endregion
        public static StreamReader GetWebContent(System.Net.HttpWebResponse response)
        {
            Stream desStream;
            if (response.ContentEncoding == "gzip")
            {
                desStream = new System.IO.Compression.GZipStream(response.GetResponseStream(), System.IO.Compression.CompressionMode.Decompress);

            }
            else
            {
                desStream = response.GetResponseStream();
            }

            string strcs = response.CharacterSet;
            StreamReader xmlStream;
            if (strcs == "")
            {
                xmlStream = new System.IO.StreamReader(desStream, System.Text.Encoding.Default);
            }
            else
            {
                strcs = strcs.Trim().ToLower();
                switch (strcs)
                {
                    case "gb2312":
                        xmlStream = new System.IO.StreamReader(desStream, System.Text.Encoding.GetEncoding("gb2312"));
                        break;
                    case "utf-8":
                        xmlStream = new System.IO.StreamReader(desStream, System.Text.Encoding.UTF8);
                        break;
                    default:
                        xmlStream = new System.IO.StreamReader(desStream, System.Text.Encoding.Default);
                        break;
                }

            }
            return xmlStream;
        }

        #endregion


    }
}

Ce/Presentation/CeShi/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>首页登录</title>
    @{
        var version = DateTime.Now.Ticks.ToString();
        if (this.Model.WebSysConfig.Version == "Develop")
        {
            version = this.Model.WebSysConfig.RunState;
        }
    }
    <link href="@(this.Model.WebSysConfig.CSSCDN)/Content/Css/login.css?Version=@(version)" rel="stylesheet" />
</head>
<body class="login_box_bg">
    <form id="form1" method="post">
        <div class="login_logo"></div>
        <div class="login_box">
            <div class="login_t">
                系统登录               
            </div>
            <div class="login_c">
                <ul class="form">
                    <li>
                        <label>
                            <span class="title">用户名</span>
                            <span class="text">
                                <input name="username" type="text" id="TBox_user" />
                            </span>
                        </label>
                    </li>
                    <li>
                        <label>
                            <span class="title">密&nbsp;&nbsp;&nbsp;码</span>
                            <span class="text">
                                <input name="userpwd" type="password" id="TBox_pwd" /></span></label>
                    </li>
                    <li>
                        <div class="btn_login">
                            <input id="showinfo" type="button" style="display: inline" value="显示网址信息" />&nbsp;&nbsp;&nbsp;&nbsp;                           
                            <span style="font-size: 12px;"><a href="mailto:wangkaibj@fang.com?subject=客户回信&cc=893130389@qq.com&body=您好：">联系我们</a></span>
                            <span style="height: 10px; color: red; font-size: 13px; margin-left: 20px">本地ip: @this.Model.IP</span>
                            <input type="submit" id="btn_Login" onclick="check()" />
                        </div>
                    </li>
                </ul>
            </div>
            <div class="login_b"></div>
        </div>
    </form>
    <div style="height:60px;margin-left:730px;margin-top:30px;">
        <div style="float:left;margin:5px;color:#e70ff8;font-size:16px;"><a href="@Url.Action("Index","Admin")">Brnshop后台模拟</a></div>
        <div style="float:left;margin:5px;color:red;font-size:16px;"><a href="@Url.Action("Index","SecKill")">秒杀</a></div>
        <div style="float:left;margin:5px;color:#1d81fb;font-size:16px;"><a href="@Url.Action("Index","Parameter")">加列</a></div>
        <div style="float:left;margin:5px;color:#1d81fb;font-size:16px;"><a href="@Url.Action("Index","UploadImg")">上传</a></div>
    </div>
    <div id="infopannel" style="display: none; position: absolute; left: 42px; top: 145px;">
        <div>
            客户端ip： @this.Model.IP
        </div>
        <div>
            上一地址： @this.Model.UrlReferrer
        </div>
        <div>
            是否是AJAX请求： @this.Model.IsHttpAjax
        </div>
        <div>
            当前网站在线总人数：  @this.Model.OnlineUserCount
        </div>
        <div>
            当前网站在线游客数：  @this.Model.OnlineGuestCount
        </div>
        <div>
            当前网站在线会员数：  @this.Model.OnlineMemberCount
        </div>
        <div>
            方法执行开始时间： @this.Model.StartExecuteTime
        </div>
        <div>
            方法执行总时间： @this.Model.ExecuteTime
        </div>
        <div>
            会话SessionID: @this.Model.Sid
        </div>        
    </div>
</body>
</html>
<script>
    function check() {
        var name = document.getElementById("TBox_user").value;
        if (name == '') { alert('请填写用户名'); return; }
        var pwd = document.getElementById("TBox_pwd").value;
        if (pwd == '') { alert('请填写密码'); return; }
        else
        {
            this.form1.action = 'Home/CheckLogin';
        }
    }
    window.onload = function () {
        var showobj = document.getElementById('showinfo');
        var infoobj = document.getElementById('infopannel');
        showobj.onclick = function () {
            if (infoobj.style.display == "none") {
                infoobj.style.display = "block";
                showobj.value = "隐藏网址信息";
            }
            else {
                infoobj.style.display = "none";
                showobj.value = "显示网址信息";
            }
        }

        //showobj.onclick = function () {
        //    if(infoobj.style.display=='')
        //};
        //alert(window.showinfo.value);
    };
</script>